name = "mkleid-preview"
main = ".open-next/server-functions/default/index.mjs"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"